[[plugins]]
# colorscheme
repo = 'jacoborus/tender.vim'
hook_add = 'colorscheme tender'


[[plugins]]
# easy comment out
repo = 'tpope/vim-commentary'


[[plugins]]
# good status bar
repo = 'vim-airline/vim-airline'


[[plugins]]
# highlight git diff sentences
repo = 'airblade/vim-gitgutter'


[[plugins]]
# display git diff
repo = 'tpope/vim-fugitive'


[[plugins]]
# lsp client for vim
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = 'source ~/.config/nvim/custom_settings/plugins/LanguageClient-neovim.vim'


[[plugins]]
# snippet
repo = 'Shougo/neosnippet-snippets'
