[[plugins]]
# colorscheme
repo = 'jacoborus/tender.vim'
hook_add = '''
  colorscheme tender
'''


[[plugins]]
# easy comment out
repo = 'tpope/vim-commentary'


[[plugins]]
# good status bar
repo = 'vim-airline/vim-airline'


[[plugins]]
# highlight git diff sentences
repo = 'airblade/vim-gitgutter'


[[plugins]]
# display git diff
repo = 'tpope/vim-fugitive'
