[[plugins]]
# colorscheme
repo = 'jacoborus/tender.vim'
hook_add = 'colorscheme tender'


[[plugins]]
# easy comment out
repo = 'tpope/vim-commentary'


[[plugins]]
# good status bar
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.config/nvim/custom_settings/plugins/airline.vim'


[[plugins]]
# highlight git diff sentences
repo = 'airblade/vim-gitgutter'


[[plugins]]
# display git diff
repo = 'tpope/vim-fugitive'


[[plugins]]
# coc
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'


[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/coc/ultisnips/rust.snippets']
let g:UltiSnipsExpandTrigger="<Down>"
'''


[[plugins]]
repo = 'preservim/nerdtree'
hook_add = 'source ~/.config/nvim/custom_settings/plugins/nerdtree.vim'
