[[plugins]]
# rust
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = 'source ~/.config/nvim/custom_settings/plugins/rust.vim'


[[plugins]]
# toml
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
# pug
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'


[[plugins]]
# yaml
repo = 'chase/vim-ansible-yaml'
on_ft = 'yaml'


[[plugins]]
# python
repo = 'nvie/vim-flake8'
on_ft = 'python'
